### ISSUE TITLE
When reloading we always go back to the start page and not the last page

### ISSUE THREAD

**Issue by XBoter** [Warlord3/Bartender#12]

**Comment by Warlord3** [comment]
Duplcate Globalkey for the Navigator

Duplicate GlobalKey detected in widget tree.

The following GlobalKey was specified multiple times in the widget tree. This will lead to parts of the widget tree being truncated unexpectedly, because the second time a key is seen, the previous instance is moved to the new location. The key was:
- [LabeledGlobalKey<NavigatorState>#fcbb8 asdf]
This was determined by noticing that after the widget with the above global key was moved out of its previous parent, that previous parent never updated during this frame, meaning that it either did not update at all or updated before the widget was moved, in either case implying that it still thinks that it should have a child with that global key.
The specific parent that did not update after having one or more children forcibly removed due to GlobalKey reparenting is:
- MediaQuery(MediaQueryData(size: Size(411.4, 797.7), devicePixelRatio: 3.5, textScaleFactor: 1.0, platformBrightness: Brightness.dark, padding: EdgeInsets.zero, viewPadding: EdgeInsets.zero, viewInsets: EdgeInsets.zero, alwaysUse24HourFormat: false, accessibleNavigation: false, highContrast: false, disableAnimations: false, invertColors: false, boldText: false, navigationMode: traditional))
A GlobalKey can only be specified on one widget at a time

**Comment by XBoter** [comment]
Das ganze ist ein hot reload bug von Flutter siehe Post. Kannst ja mal ausprobieren und wenn es weg ist den Bug schließen
https://stackoverflow.com/questions/49371221/duplicate-globalkey-detected-in-widget-tree

**Comment by XBoter** [comment]
Das ganze ist ein hot reload bug von Flutter siehe Post. Kannst ja mal ausprobieren und wenn es weg ist den Bug schließen
https://stackoverflow.com/questions/49371221/duplicate-globalkey-detected-in-widget-tree
@Warlord3

**Comment by XBoter** [comment]
> Duplcate Globalkey for the Navigator
> 
> Duplicate GlobalKey detected in widget tree.
> 
> The following GlobalKey was specified multiple times in the widget tree. This will lead to parts of the widget tree being truncated unexpectedly, because the second time a key is seen, the previous instance is moved to the new location. The key was:
> 
> * [LabeledGlobalKey#fcbb8 asdf]
>   This was determined by noticing that after the widget with the above global key was moved out of its previous parent, that previous parent never updated during this frame, meaning that it either did not update at all or updated before the widget was moved, in either case implying that it still thinks that it should have a child with that global key.
>   The specific parent that did not update after having one or more children forcibly removed due to GlobalKey reparenting is:
> * MediaQuery(MediaQueryData(size: Size(411.4, 797.7), devicePixelRatio: 3.5, textScaleFactor: 1.0, platformBrightness: Brightness.dark, padding: EdgeInsets.zero, viewPadding: EdgeInsets.zero, viewInsets: EdgeInsets.zero, alwaysUse24HourFormat: false, accessibleNavigation: false, highContrast: false, disableAnimations: false, invertColors: false, boldText: false, navigationMode: traditional))
>   A GlobalKey can only be specified on one widget at a time

Das ganze ist ein hot reload bug von Flutter siehe Post. Kannst ja mal ausprobieren und wenn es weg ist den Bug schließen
https://stackoverflow.com/questions/49371221/duplicate-globalkey-detected-in-widget-tree
@Warlord3

**Comment by Warlord3** [comment]
Das kommt aber auch wenn du von light mode auf dark mode wechselts

**Comment by XBoter** [comment]
Ok schaue mir das ganze nochmal an
